### PR TITLE
Add Inertia v2 Support

### PR DESCRIPTION
**Pull request by onlime**
Please merge https://github.com/lepikhinb/momentum-modal/pull/76 and publish this Vue3 plugin. It has been extensively tested from our side in a larger app and works flawlessly with Inertia v2.0.0

### CODE REVIEW

**Review by raftalks — APPROVED** [review]

**Comment by onlime** [comment]
@lepikhinb are you still planning to maintain Momentum Modal? It's a great project and it works absolutely flawlessly on Inertia v2, so we would all greatly appreciate if you could merge and publish it. 🙏

---
## `momentum-modal` (npm)

For those who can't wait and don't want to use `npm i --force` (as now all other packages seem to be compatible with Inertia v2), you can install directly from my other [`inertia-v2-build`](https://github.com/onlime/momentum-modal-plugin/tree/inertia-v2-build) branch like this:

```bash
$ npm i onlime/momentum-modal-plugin\#inertia-v2-build --save-dev
```

... which will put the following in your `package.json`:

```json
    "devDependencies": {
        "momentum-modal": "github:onlime/momentum-modal-plugin#inertia-v2-build",
    }
```

I have bumped all deps and added a `prepare` script there, so `momentum-modal-plugin` will be automagically built upon install.

> [!IMPORTANT]
> Make sure you have `prettier` installed globally (e.g. `brew install prettier`) to get the build running.

## `based/momentum-modal` (Composer)

For PHP `based/momentum-modal` package (https://github.com/lepikhinb/momentum-modal/pull/76), just add this to your `composer.json`:

```json
    "require": {
        "based/momentum-modal": "dev-inertia-v2",
    },
    "repositories": [
        {
            "type": "git",
            "url": "https://github.com/onlime/momentum-modal.git"
        }
    ],
```

**Comment by gainlinejono** [comment]
I've asked @lepikhinb a couple of times if this could be merged and he's said he would, Inertia 2.0 has been in beta for a while and has been released now for a week. There's been plenty of time to merge this in. 

However, we've moved onto using Inertia UI's Modal plugin instead as we're already using the Inertia UI Table and it's compatible with Inertia 2.0.

**Comment by onlime** [comment]
> I've asked @lepikhinb a couple of times if this could be merged and he's said he would, Inertia 2.0 has been in beta for a while and has been released now for a week. There's been plenty of time to merge this in.

yes, but sadly he seems to have disappeared from the ground since the Lemon Squeezy takeover... just guessing.

> However, we've moved onto using Inertia UI's Modal plugin instead as we're already using the Inertia UI Table and it's compatible with Inertia 2.0.

Good choice! I'm working very closely together with @pascalbaljet - he's the guy behind Inertia UI. Pascal is very very much into it! A super smart guy and all his passion goes into InertiaUI. Can highly recommend as he delivers super clean tested code that just works and has an eye for simplicity.

I'm still stuck with Momentum Modal as I customized it quite a bit, and actually does the job quite well.

**Comment by laserhybiz** [comment]
[another alternative](https://github.com/emargareten/inertia-modal)

**Comment by lepikhinb** [comment]
Sorry guys. Getting back 👌🏻 Thanks for the heads up

**Pull request merged**
